// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vatdypuyczcrlbzhxoxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhdGR5cHV5Y3pjcmxiemh4b3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4OTUxODMsImV4cCI6MjA3ODQ3MTE4M30.35ELcu01O7cZbEtfNwB73PHBKEHyLBZQsenlCwNkeuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});